GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGFlOGUzMWJjMTMxMGU0NmJjNDVlYzQiLCJpYXQiOjE2ODk2ODA2NzUsImV4cCI6MTY4OTY4MDY5MCwiYXVkIjoiNjRhZThlMzFiYzEzMTBlNDZiYzQ1ZWM0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.jIdfpGAFaWT-EPPR97M3fP0HrNdm7HbiMqcwttaMB5U

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"uzumakki@gmail.com",
    "password":"12345"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"uzumakki@gmail.com",
    "password":"12345"
}