GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGFlOGUzMWJjMTMxMGU0NmJjNDVlYzQiLCJpYXQiOjE2OTQ4NTcyMTMsImV4cCI6MTY5NDg1NzIyOCwiYXVkIjoiNjRhZThlMzFiYzEzMTBlNDZiYzQ1ZWM0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.UNSNVoQgNbFSEtbjofu-jNWVpRmJvMW9XQQcOQ4kNpU

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"uzumakki@gmail.com",
    "password":"12345"
}





### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"uzumakki@gmail.com",
    "password":"12345"
}

### Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json


{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGFlOGUzMWJjMTMxMGU0NmJjNDVlYzQiLCJpYXQiOjE2OTQ4NTcyMTMsImV4cCI6MTcyNjQxNDgxMywiYXVkIjoiNjRhZThlMzFiYzEzMTBlNDZiYzQ1ZWM0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.VMiMFWIf1qXuR1YZetulZ0F2mHZTMwGPH-xNrPQd9uA"
}