GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGFlOGUzMWJjMTMxMGU0NmJjNDVlYzQiLCJpYXQiOjE3MDAwNTY2MzksImV4cCI6MTcwMDA1NjY1NCwiYXVkIjoiNjRhZThlMzFiYzEzMTBlNDZiYzQ1ZWM0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.fKI71iKAKJd8ga_wLWgRJTckEETv61hEK_KqzlLZu_o

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"uzumakki@gmail.com",
    "password":"12345"
}





### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"uzumakki@gmail.com",
    "password":"12345"
}

### Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json


{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGFlOGUzMWJjMTMxMGU0NmJjNDVlYzQiLCJpYXQiOjE2OTQ4NTcyMTMsImV4cCI6MTcyNjQxNDgxMywiYXVkIjoiNjRhZThlMzFiYzEzMTBlNDZiYzQ1ZWM0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.VMiMFWIf1qXuR1YZetulZ0F2mHZTMwGPH-xNrPQd9uA"
}


### Logout
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGFlOGUzMWJjMTMxMGU0NmJjNDVlYzQiLCJpYXQiOjE3MDAwNTYwNTYsImV4cCI6MTczMTYxMzY1NiwiYXVkIjoiNjRhZThlMzFiYzEzMTBlNDZiYzQ1ZWM0IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.szghOoqgRYg4qJmyqh364DhPxLDFRzkxYFPFp0ChRuE"
}